# Generated by Django 4.1.7 on 2023-03-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner_id", models.IntegerField()),
                ("content_type", models.PositiveSmallIntegerField()),
                ("owner_name", models.CharField(max_length=255)),
                ("thumb_url", models.URLField(blank=True, null=True)),
                ("cover_url", models.URLField(blank=True, null=True)),
                ("description", models.TextField()),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("total_score", models.IntegerField()),
                ("total_tasks", models.IntegerField()),
                ("is_netology", models.BooleanField()),
                ("bg_url", models.URLField(blank=True, null=True)),
                ("video_url", models.URLField(blank=True, null=True)),
                ("demo", models.BooleanField()),
                ("unchangeable", models.BooleanField()),
                ("include_weekly_report", models.BooleanField()),
                ("custom_author_names", models.CharField(max_length=255)),
                ("custom_contents_link", models.URLField(blank=True, null=True)),
                ("hide_viewer_navigation", models.BooleanField()),
                ("duration", models.TimeField(blank=True, null=True)),
                ("account_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=150)),
                ("lang", models.CharField(max_length=3)),
                ("external_id", models.CharField(max_length=150)),
                ("role_id", models.IntegerField()),
                ("auth_type", models.IntegerField()),
                ("labels", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Types",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.ManyToManyField(to="teachbase.course")),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("icon_url", models.URLField(blank=True, null=True)),
                ("small_url", models.URLField(blank=True, null=True)),
                ("thumb_url", models.URLField(blank=True, null=True)),
                (
                    "icon_content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("draft", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="teachbase.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Materials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("section_position", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("section_id", models.IntegerField()),
                ("course_id", models.IntegerField()),
                ("account_id", models.IntegerField()),
                ("position", models.IntegerField()),
                ("is_external", models.BooleanField()),
                (
                    "external_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("has_file", models.BooleanField()),
                ("extension", models.CharField(blank=True, max_length=255, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "file_content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("category", models.CharField(max_length=255)),
                ("file_size", models.IntegerField()),
                ("size", models.IntegerField(blank=True, null=True)),
                ("thumb_url", models.URLField(blank=True, null=True)),
                ("view_url", models.URLField(blank=True, null=True)),
                ("view_url_cors", models.URLField(blank=True, null=True)),
                ("poster_url", models.URLField(blank=True, null=True)),
                ("status_code", models.CharField(max_length=255)),
                (
                    "status_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("section", models.ManyToManyField(to="teachbase.section")),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("phone", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("role_id", models.SmallIntegerField()),
                ("auth_type", models.SmallIntegerField()),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.ManyToManyField(to="teachbase.course")),
            ],
        ),
    ]
